/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 TQ-1910 applied modifier.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jogger({...props}) {
  const { nodes, materials } = useGLTF('/TQ-1910 applied modifier.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.STITCH_COLLAR.geometry} material={materials['NYLON LINING']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.STITCH_EYESTAY.geometry} material={materials['SUEDE BURGUNDY']} position={[0.304, 0.728, -0.089]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.222, 0.227]} />
      <mesh geometry={nodes.STITCH_HEEL_COUNTER.geometry} material={materials['SUEDE DK GRAY HEEL COUNTER']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.249, 0.221, 0.222]} />
      <mesh geometry={nodes.STITCH_MEDIAL_DECO.geometry} material={materials['NYLON LINING']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.STITCH_TOECAP_.geometry} material={materials.suede} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.25, 0.222, 0.223]} />
      <mesh geometry={nodes.EVA.geometry} material={materials.EVA} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.EVA_COLORED_STRIPE.geometry} material={materials['EVA MIDSOLE STRIPE BURGUNDY']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.EVA_FOXING.geometry} material={materials.EVA} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.TPR.geometry} material={materials['TPR GUM']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.SOLEPLATE_EVA.geometry} material={materials.EVA} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.LOGO_MUSTACHE_DH_.geometry} material={materials['LOGO MUSTACHE']} position={[-2.785, 0.647, -0.173]} rotation={[1.574, -0.453, 1.549]} scale={4.388} />
      <mesh geometry={nodes.LOGO_SIDE_WORDMARK_.geometry} material={materials['LOGO SIDE']} position={[-0.413, 0.612, -0.608]} rotation={[-1.705, -0.418, -0.231]} scale={[-11.684, -15.342, -10.815]} />
      <mesh geometry={nodes.EYESTAY.geometry} material={materials['SUEDE BURGUNDY']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.HEEL_COUNTER.geometry} material={materials['SUEDE DK GRAY HEEL COUNTER']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.INSOLE.geometry} material={materials.INSOLE} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.LACEKEEPER.geometry} material={materials['NYLON LACE KEEPER']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.LACES.geometry} material={materials['LACE COTTON']} position={[-0.024, 1.322, 0.056]} rotation={[0.011, -0.083, -0.012]} scale={[0.335, 0.415, 0.415]} />
      <group position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['NYLON LINING']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['NYLON LINING']} />
      </group>
      <mesh geometry={nodes.MUSTACHE.geometry} material={materials['SUEDE DK GRAY MUSTACHE']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <group position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['NYLON UPPER']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['NYLON LINING']} />
      </group>
      <mesh geometry={nodes.SIDEWALL_OVERLAY.geometry} material={materials['WHITE LEATHER SIDE OVERLAY']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.SIDEWALL_UNDERLAY.geometry} material={materials['SUEDE SIDE UNDERLAY']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.TOE_CAP.geometry} material={materials['SUEDE TOE CAP']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.TONGUE.geometry} material={materials['NYLON TONGUE']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.TONGUE_BINDING.geometry} material={materials['NYLON LINING']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
      <mesh geometry={nodes.TONGUE_LABEL.geometry} material={materials['TONGUE LABEL NYLON']} position={[-0.05, -0.68, 0.031]} rotation={[0.013, 0.035, -0.012]} scale={[0.248, 0.221, 0.221]} />
    </group>
  )
}

useGLTF.preload('/TQ-1910 applied modifier.gltf')
